# -*- coding: utf-8 -*-
"""QUIZ1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TDT1GPCwp9aFhkcHPN5uL6ktl9ssOzHi

# *Quiz 1*

## Creating a list with random number
"""

#USING FOR LOOP
import random
mylist=[]
for i in range(0,30):
    n=random.randint(0,100)
    mylist.append(n)
print(mylist)

# USING LIST COMPREHENSION
mylist=[random.randint(0,100) for i in range(0,30)]
print(mylist)

"""## Class Method returning name and id of the object"""

class Myclass():
 
    #defining init method
    def __init__(self,name,id):
      self.name=name
      self.id=id


    #Defining my methon
    def method1(self):
      name=self.name
      id=self.id
      return name, id

## Calling Myclass
Myobject=Myclass("Cesar", 1)
print(Myobject.method1())

## Calling Myclass
Myobject=Myclass("Eric", 2)
print(Myobject.method1())

"""## Finding the smallest missing positive integer given an unsorted integer array"""

#unsorted array
myarray= [3,4,-1,1]
#myarray= [-3,-2,-1,0,1,3,4,6,8]
myarray.sort()
positives = [i for i in myarray if i >= 0]

missing_pos=[]
for i in range(len(positives)+1):
    try:
        diff=positives[i+1]- positives[i]
        if diff>1:
           missing_pos.append(positives[i]+1)
    except:
          break
print(missing_pos)

"""## Remove duplicates"""

# Remove duplicates
weekdays = ['sun','mon','tue','sun','mon','tue','wed','thu','fri','wed','thu','fri','sat']
myset=set(weekdays)
weekdays=list(myset)
print(weekdays)