# -*- coding: utf-8 -*-
"""WordsCount.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1272_akYnIJ55wYcTpAGCyCAdZ8ct-Dbs

# *Words Count*
"""

def word_count(str):
	    counts = dict()
	    words = str.split()
	
	    for word in words:
	        if word in counts:
	            counts[word] += 1
	        else:
	            counts[word] = 1
	
	    return counts
	
print( word_count('hey hey how you doing'))

# Read the File.txt
mytext = "/content/shakespeare.txt"
mytext = open(example1, "r")

# Read the file
FileContent = mytext.read()
FileContent

# Assigning the Funtion output to the new variag
counts=word_count(FileContent)
print(counts)

[print(key, value) for key, value in counts.items()]

# Saving the dictionary counts in file
with open("newfile.txt", "w") as myfile:
    for key in counts:
        myfile.write(key+ ":" + str(counts[key]) + "\n")