# -*- coding: utf-8 -*-
"""WordsCount.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1272_akYnIJ55wYcTpAGCyCAdZ8ct-Dbs

# *Words Count PYTHON*
"""

import string

def word_count(str):
	    counts = dict()
	    words = str.split()
	
	    for word in words:
	        if word.lower() in counts:
	            counts[word] += 1
	        else:
	            counts[word] = 1
	
	    return counts

# Read the File.txt
myfile = "/content/shakespeare.txt"
mytext= open(myfile, "r")

import string
# Read the file
FileContent = mytext.read()
FileContent

# remove punctuation from the string
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
no_punct = ""
for char in FileContent:
   if char not in punctuations:
       no_punct = no_punct + char
       
# display the unpunctuated string
no_punct = no_punct.lower()
counts=word_count(no_punct)
print(counts)

[print(key, value) for key, value in counts.items()]

# Saving the dictionary counts in file
with open("outfile.txt", "w") as myfile:
    for key in counts:
        myfile.write(key+ ":" + str(counts[key]) + "\n")